apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  ports:
  - nodePort: 31234
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: backend
  type: NodePort
status:
  loadBalancer: {}